#--------------------------------------------------------------
# Jenkins docker-compose
#--------------------------------------------------------------
version: '3'

#---NETWORKS---------------------------------------------------
networks:
  default:
    external:
      name: common

#---VOLUMES ---------------------------------------------------
volumes:
  data:

#---SERVICES---------------------------------------------------
services:
  jenkins:
    build: ./jenkins
    image: 'local/jenkins'
    ports:
      - '50000:50000'
      - '8081:8443'
    volumes:
      - 'data:/var/jenkins_home'
    environment:
      JAVA_OPTS: -Duser.timezone=Asia/Tokyo
