version: '3'

services:
  ubuntu-dev:
    container_name: ubuntu-dev
    image: ubuntu-dev
    build:
      context: ./ubuntu
      dockerfile: Dockerfile
    cap_add:
      - SYS_ADMIN
    security_opt:
      - seccomp:unconfined
    privileged: true
    command:
      - /sbin/init
